### ISSUE TITLE
trigger event and parse URL as argument for workflow

### ISSUE THREAD

**Issue by forkbabu** [peter-evans/slash-command-dispatch#103]
How to do 

`/download https://www.youtube.com/watch?v=VNs_cCtdbPc`

and then `youtube-dl` takes over from there

Goal is to download this song as an artifact. [Example here](https://github.com/forkbabu/Youtuber/actions/runs/701484842) 

Trying to do this in https://github.com/forkbabu/Youtuber

**Comment by peter-evans** [comment]
Hi @forkbabu 

You can access the parameters sent with the slash command from the `slash_command` context sent in the payload. See this section of the documentation: https://github.com/peter-evans/slash-command-dispatch#slash_command-context

There are also a number of examples that use parameters that might help here:
https://github.com/peter-evans/slash-command-dispatch/blob/master/docs/examples.md
