### ISSUE TITLE
Dispatch event not received?

### ISSUE THREAD

**Issue by janolaveide** [peter-evans/slash-command-dispatch#12]
This is most likely a misunderstanding on my part, but my action (https://github.com/navikt/fpsoknad-mottak/blob/master/.github/workflows/ping-command.yml) that receives the custom type on repository_dispatch is never triggered. The event dispatcher https://github.com/navikt/fpsoknad-mottak/blob/master/.github/workflows/dispatch.yml reports successful delivery of the event, but nothing happens in the handler. Any help greatly appreciated, as this action looks very useful if I can get it to work

**Comment by Nuru** [comment]
@janolaveide It would probably help if you added a clear warning to the README that the standard `GITHUB_TOKEN` does not have adequate permission to dispatch an event, even to the same repo.
