### ISSUE TITLE
Dispatch reports success even on failure

### ISSUE THREAD

**Issue by Nuru** [peter-evans/slash-command-dispatch#31]
Because I was using the `GITHUB_TOKEN` as the `token`, dispatched events were rejected by GitHub. However, the command log still showed success:
```
Command 'test' to be dispatched.
Command 'test' dispatched to 'Nuru/test' with event type 'test-command'.
```
`slash-command-dispatch` should report a failure if the response to the dispatch API call is 403 (or any other error code)

**Comment by peter-evans** [comment]
@Nuru Unfortunately, the action cannot report a failure because the GitHub API accepts the requests. That's why it doesn't fail currently. I don't know for sure if this is intentional design by GitHub, but most likely it is.

I saw from [this comment](https://github.com/peter-evans/slash-command-dispatch/issues/12#issuecomment-592791327) that it wasn't clear to you that the `GITHUB_TOKEN` could not be used. I've tried to make that as clear as possible throughout the documentation. The [getting started guide](https://github.com/peter-evans/slash-command-dispatch/blob/master/docs/getting-started.md) also walks through the whole setup.

**Comment by Nuru** [comment]
@peter-evans I know you did try to make it clear `GITHUB_TOKEN` could not be used, but it's still not clear enough. How about if you change the start of Action Inputs to something like this:


| Input | Description | Default |
| --- | --- | --- |
| `token` | A `repo` scoped [PAT](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line). Note: `GITHUB_TOKEN` will not work here.|  (**required**) |
| `reaction-token` | `GITHUB_TOKEN` or a `repo` scoped [PAT](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line). |  `${{ token }}` |

As for the lack of feedback from GItHub API, I'm surprised, but I confirmed it: GitHub accepts the request but does not act on it.
```
curl -isSL --request POST --url https://api.github.com/repos/Nuru/test/dispatches \
  --header 'authorization: Bearer ${{ GITHUB_TOKEN }}' \
  --header 'content-type: application/json' \
  --data '{ "event_type": "curl-test" }'
```
returns
```
HTTP/1.1 204 No Content
Server: GitHub.com
Date: Sat, 29 Feb 2020 01:44:41 GMT
Status: 204 No Content
X-RateLimit-Limit: 1000
X-RateLimit-Remaining: 994
X-RateLimit-Reset: 1582941466
X-GitHub-Media-Type: github.v3; format=json
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: 0740:40BA:9C3F5F:1767BBB:5E59C209
```

**Comment by peter-evans** [comment]
Updated the README to try and make it even clearer. Thanks.
