### ISSUE TITLE
Feature Request: trim whitespace, allow command embedding

### ISSUE THREAD

**Issue by Nuru** [peter-evans/slash-command-dispatch#32]
Currently, any trailing whitespace (or at least trailing \r\n) attaches to what it proceeds, making equality tests fail. As a result, [this](https://github.com/peter-evans/slash-command-dispatch/pull/8#issuecomment-592658418)
```
/hello-world
```
dispatches the `hello-world` demo but [this](https://github.com/peter-evans/slash-command-dispatch/pull/8#issuecomment-593699642)
```
/hello-world

```
does not. Similarly, if a command takes arguments, then 
```
/command param1

```
yields JSON
```json
"arg1": "param1\r\n"
```
Which can cause the command to fail if it is expecting `param1` and does not recognize `param1
`. I would like leading and trailing whitespace trimmed by default, or at least as an option. This comes up in practice when people copy and paste commands, such as when one command says
```
Next step, choose either:

/operation approve
/operation deny

```

Going a step further, I would like to allow real comments to be included in the same comment as the ChatOps command. This would allow people to, well, comment on why they are issuing a command. I would simply require the ChatOps command be on a line by itself.

Going one more step, we could allow multiple commands in a comment. That definitely should be something configurable (enabled/disabled), but I would use it if it were an option.

**Comment by peter-evans** [comment]
@Nuru Thank you for these feature suggestions.

**Trimming whitespace**
This could almost be considered a bug. I will try and get that fixed soon.

**Allow comments with the command on a line by itself**
I understand your use case for this and I think it would be a good feature. However, it could get tricky to implement and difficult for users to know for sure which parts of their comment could be executed as a command. For example, the comment blocks in your post above would need to be parsed and ignored. What I think might work is for this action to enforce that a command must be the first line of the comment. Anything after that is ignored. This would be easier to implement and easier for users to understand. I don't want to create a situation where users could accidentally issue commands they didn't intend to.

**Comment by peter-evans** [comment]
@Nuru I've updated `v1` with a fix. The action was already expecting the command to start from the first character of the command. I've additionally made it ignore any content after the first line, so you are free to use the rest of the comment for anything you like.

There's an example here from my testing:
https://github.com/peter-evans/slash-command-dispatch/issues/33#issuecomment-593878873

As for multiple commands in a single comment, I'll keep that on my list as a possible feature to add in future.

**Comment by Nuru** [comment]
> **Allow comments with the command on a line by itself**
> I understand your use case for this and I think it would be a good feature. However, it could get tricky to implement and difficult for users to know for sure which parts of their comment could be executed as a command. For example, the comment blocks in your post above would need to be parsed and ignored. What I think might work is for this action to enforce that a command must be the first line of the comment. Anything after that is ignored. This would be easier to implement and easier for users to understand. I don't want to create a situation where users could accidentally issue commands they didn't intend to.

@peter-evans  I agree and sorry if I did not make clear: I would support a requirement that the `/` be the first character on the line in order for the line to be considered a ChatOps command.  I would further enforce that the entire line (up to but not including trailing whitespace and the \r\\n) be considered part of the ChatOps command. 

For both cases, it is important to me that the `/` not be required to be the first character of the comment (that is, either be the first character of the comment or be immediately proceeded by a newline character).  I definitely want to interpret
```

/hello-world

```
as a ChatOps command. 

As for multiple commands in a single comment, I agree that is a bigger feature with greater impacts, and support taking some time to think it through and be careful about the implementation and consequences.

**Comment by peter-evans** [comment]
Thank you for sharing your opinion. The main concern for me is that the action behaviour is understandable and easy to use. Especially since it could be used to perform some tasks where the user needs to take care, like deploying to production. It should be *very clear* what part of the comment is "executable." I think having a simple rule that only the first line of the comment is executable is the approach I would like to take.

With that in mind, I do not want to interpret leading newlines before the command as "the first line." This is not understandable to a lay user. The user might be deliberately putting the command on the second line to make it *not executable*.

I might consider stripping other types of leading whitespace (spaces, tabs, etc) from the first line, but not newlines.

**Comment by Nuru** [comment]
@peter-evans OK, we disagree about requiring the command to be on the first line, but it is your project, your call, and I can certainly understand your rationale. I won't try further to convince you to make changes to the implementation, but I will ask you to include a section in the README that explains how ChatOps commands are parsed, as you have explained above. Particularly:
-  `/` must be the first character of the comment. `/command` appearing anywhere else will not be interpreted as a command.
- The command extends to the last non-whitespace character on the first line and everything after that is ignored. This allows you to add information about the command to the comment.

Thank you again for making the whitespace parsing changes promptly and for providing this valuable library in the first place.

**Comment by peter-evans** [comment]
@Nuru I'm still thinking about this and might reconsider if I can come up with a safe way to implement it. I think I might be able to change the action to loop the entire logic over each line until it finds a command. It would probably be a pretty major refactor, but there is not really any other way to do it. At that point I've basically implemented multiple commands in a single comment.

Then of course there is markdown code blocks to deal with, where the lines before and after start with 3 backticks. Can you think of any other edge cases where a line should *not* be interpreted as a command?

Whatever I decide to do in the end I will explain how it works clearly in the README.

**Comment by Nuru** [comment]
@peter-evans Thank you for continuing to think about this. It had not occurred to me that you practically need to implement a full Markdown parser to make this work, as I would say you should ignore any commands inside code blocks or quoted blocks, or as continuation lines of lists, etc. 

My thinking today is there are 3 feature requests here:
1. Allow whitespace, including newlines, before the first `/`, so the command can have a line or two of whitespace above it.
2. Allow comments above the first command.
3. Allow multiple commands per comment.

I'm in favor of including (1) in this issue and enabling it, possibly as a non-default configuration setting.

Now that I see more of the complexity of the request, I think you or I should open separate feature request issues for (2) and (3) and see how many votes they attract before moving ahead with them. My guess is the demand for the features is not going to justify the work to implement them safely.

**Comment by peter-evans** [comment]
Sorry to keep going back and forth on this. I spent a few hours today writing some tests to try and parse comments into multiple potentially valid lines. I now see that it's even more complex than I first imagined. It pretty much would involve a full markdown/html parser to figure out exactly what parts of the comment are executable. With experience comes a great desire to keep things simple and maintainable! So, at least for now, I'm going to stick with the parsing rules I mentioned in [this comment](https://github.com/peter-evans/slash-command-dispatch/issues/32#issuecomment-594956749). I will update the README to make it clear.

**Comment by Nuru** [comment]
@peter-evans As I said in my [previous comment](https://github.com/peter-evans/slash-command-dispatch/issues/32#issuecomment-595907275), I came to the same conclusion, that you would need a full Markdown parser to figure out what is a valid command and what is somehow quoted, so I am fine taking back my requests 2 (embedded commands) and 3 (multiple commands). 

I sill would like you to allow/ignore space, tab, carriage-return, and new-line characters before the first `/` though, and not insist that the `/` be the very first character of the comment.

**Comment by peter-evans** [comment]
@Nuru As I mentioned in [this comment](https://github.com/peter-evans/slash-command-dispatch/issues/32#issuecomment-594956749), I don't think it makes any sense to trim newlines from the start of the comment. However, I've made another small fix to trim any other types of whitespace around the contents of the first line.
