### ISSUE TITLE
Which permissions do I need to grant to a github app to issue a token for this action?

### ISSUE THREAD

**Issue by k7k0** [peter-evans/slash-command-dispatch#359]
In our org, we can't create PAT. Instead, we use GitHub apps in combination with [actions/create-github-app-token](https://github.com/actions/create-github-app-token). I couldn't find which permissions to grant to the app to work with this action.

**Comment by peter-evans** [comment]
Hi @k7k0 

I think it's `contents: write` and in "Organization permissions" you'll need `members: read`.

**Comment by k7k0** [comment]
Thanks Peter. I had to grant repository Pull-Request read only as well 👍

**Comment by aaronsteers** [comment]
@k7k0, @peter-evans - I ran into the same question...

Is this correct:

```
        permission-contents: write
        permission-pull-requests: read
        permission-issues: read
        permission-members: read
```

And do we need anything additional to post comment reactions, assuming the same token is used for reactions?

It would be helpful to have these in the docs. Happy to contribute if helpful.
