### ISSUE TITLE
Integrate permission check with Github's CODEOWNERS

### ISSUE THREAD

**Issue by douglascamata** [peter-evans/slash-command-dispatch#61]
I would love to be able to only people CODEOWNERS to be able to dispatch commands in some pull requests.

This is a nice way of controlling permissions without having to give other people direct access to the repository.

**Comment by peter-evans** [comment]
Hi @douglascamata 

My understanding is that codeowners should already have `write` access to the repository. So I'm not sure that using codeowners is the right way to solve this. It also looks like it would be complicated to parse.

> The people you choose as code owners must have write permissions for the repository.

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

What I might be able to do is add configuration to allow specifying a list of users that have permission to execute the command, regardless of their role.

Something like this:
```
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            [
              {
                "command": "test",
                "permission": "write",
                "issue_type": "pull-request",
                "users": [ "peter-evans", "douglascamata" ]
              }
            ]
```

**Comment by douglascamata** [comment]
@peter-evans damn, I don't know how I didn't see that. I wanted exactly to allow people that do not have write access to the repository to be able to approve pull request to files modified in some specific folders.

Thanks for the heads up. As this is a limitation of Github's Code Owners feature at the moment, I'll be closing the issue.
