### ISSUE TITLE
Allow for triggering workflow_dispatch 

### ISSUE THREAD

**Issue by mrchief** [peter-evans/slash-command-dispatch#68]
Github has a new event called [workflow_dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) which is similar to `repository_dispatch` but allows you to trigger workflows from other branches. 

It'd be nice to have an option to trigger `workflow_dispatch` via actions passing all inputs (named args etc).

https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by peter-evans** [comment]
Hi @mrchief

I saw the announcement and I'm currently working on implementing this feature!
Good to know someone is interested in using it.

**Comment by peter-evans** [comment]
@mrchief I'm now testing `v2` of this action which is being developed in the `dev` branch and currently tagged as `v2-beta`. This includes support for `workflow_dispatch`. It would be great to get your feedback if you have time to test it. 

```
uses: peter-evans/slash-command-dispatch@v2-beta
```

See the full change notes here: https://github.com/peter-evans/slash-command-dispatch/blob/dev/docs/updating.md#updating-from-v1-to-v2

Documentation for workflow dispatch is here: https://github.com/peter-evans/slash-command-dispatch/blob/dev/docs/workflow-dispatch.md

**Comment by peter-evans** [comment]
Merged and released in `v2`

**Comment by mrchief** [comment]
@peter-evans Thanks for the quick update. I'll try and let you know if I run into any issues.
