### ISSUE TITLE
mention that created commit will not trigger builds

### ISSUE THREAD

**Issue by staabm** [peter-evans/slash-command-dispatch#7]
IMO it needs to be mentioned that commits triggered via this action without a proper PAT will not trigger github actions/builds.

for use-cases like e.g. fixing code-style via a slash-command that results in a caveat that renders the use-case useless (or at least a workaround or some guidance is required on how to handle that).

even with a PAT it works only in same-repo based Pull Requests and not on forks (as far as I am informed correctly)

do you have a proposal/workaround for this kind of scenario?

**Comment by peter-evans** [comment]
Yes, this action requires a `repo` scoped PAT as stated in the [inputs section here](https://github.com/peter-evans/slash-command-dispatch#action-inputs). The main reason for this is that creating repository dispatch events requires it.

I'm not sure why you think it won't trigger builds. Using a PAT for commits will always trigger a build. Only the `GITHUB_TOKEN` has those restrictions.

I actually created this action for the very purpose of working around the fact that there are restrictions on events created by forked repositories. My findings about those restrictions are detailed [here](https://github.com/peter-evans/create-pull-request/issues/71#issuecomment-553228339).

If you are looking for a solution that doesn't require any use of a PAT then I'm afraid you are out of luck. It doesn't exist at the moment. If you are willing to use a PAT then this action opens up a lot of use cases, including the ones you mentioned. (Code styling via slash command will work just fine).

The [demo here](https://github.com/peter-evans/slash-command-dispatch/pull/6) is an example of a PR created by a fork. The slash command works fine, but yes, you need to use a `repo` scoped PAT.

I'm not sure what kind of workaround you are looking for. To me, this **is** the workaround, and why I created this action. 😄

**Comment by peter-evans** [comment]
@staabm If you don't mind I'm going to close this issue. We can keep discussing here and I will try and help you with whatever use case you might have.
