### ISSUE TITLE
feat: support "triage" permission level

### ISSUE THREAD

**Issue by TGTGamer** [peter-evans/slash-command-dispatch#72]
Would like to see an update to support the role of "triage". Should be fairly simple xD

**Comment by peter-evans** [comment]
Hi @TGTGamer 

The action currently uses [this API](https://docs.github.com/en/rest/reference/repos#get-repository-permissions-for-a-user) which works for both user repositories and org repositories. It only returns `admin`, `read`, `write` and `none`.

I will look into adding the `triage` and `maintain` org roles. I think it's doable but I'll need to use a different API and cover cases such as setting `triage` permission for a command where the target repository isn't an org repo, etc.

**Comment by peter-evans** [comment]
Released and updated the `v2` tag
