### ISSUE TITLE
Questions: Setup for advanced use

### ISSUE THREAD

**Issue by TGTGamer** [peter-evans/slash-command-dispatch#73]
Heya @peter-evans thanks for inviting me to this repo through StackOverflow. Got a few questions I'd like to run through before I switch entirely over to this workflow within my repository. 

The end goal is to have Chatops commands which are specifically available to individual users to reduce the required work of contributors when using open source projects. So the following would make sense: 

| Command | Permission Required | Description |
| --- | --- | --- |
| /first-timer | _First_Timer_ or _None_ | Introduces inexperienced github users to our project
| /createbranch | _None_ | Creates a branch for an open issue |
| /revert | **Write** | Reverts a previous commit automatically |
| /rebase | **Write** or _PR Owner_ | Rebases a pull request automatically |
| /ban [user] | **Admin** | Automatically takes action to ban a user |

_Italics_ author associations relative to the event & repo
**Bold** are  github permissions

So I know that it is possible within this application to do all the GitHub permissions, however, I still need to be able to check what association this user has to the event that was triggered and the overall repository.

Any ideas?

**Comment by peter-evans** [comment]
Hi @TGTGamer 

The action controls permissions for slash commands _it dispatches_ by repository permissions. However, you can still write your own logic in the `repository_dispatch` workflow to decide whether to execute the command or not based on other conditions. In your case, you are interested in the author association of the user executing the command. In the target workflow you can access this information from the following context parameter.

```
${{ github.event.client_payload.github.payload.comment.author_association }}
```
See [here](https://github.com/peter-evans/slash-command-dispatch#accessing-contexts) for more detail about the different contexts that are sent with the dispatch.

Using that context you can tailor the response by the command. For example:
```yml
      - if: github.event.client_payload.github.payload.comment.author_association == 'FIRST_TIMER'
```

To check if the user that made the comment is the PR author:
```yml
      - if: github.event.client_payload.github.payload.comment.user.login == github.event.client_payload.pull_request.user.login
```

You can check all the available contexts by dumping them in the target workflow.
```yml
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
```

**Comment by peter-evans** [comment]
Closing this for now. Feel free to continue commenting if you need further help.

**Comment by TGTGamer** [comment]
Just wanted to drop a line to say I finally found time to sit down and integrate this. I am actually using my own action to pass the configuration into a secret.SETTINGS whenever it gets changed, which can be used by your action in the config option. 

I would love to integrate my action directly with yours so they work side by side a bit cleaner at some point  (I'll throw a PR). 

Other than that, I want to say this has worked a treat and unlike other actions which I am slowly re-coding, I don't think there are any improvements other than #72 which you've already completed. 

^_^

**Comment by peter-evans** [comment]
@TGTGamer Glad you got things working well. 👍 

Please let me know what feature you are interested in adding to this action before you spend time working on it and raising a PR. I'm being very careful about features I add to keep complexity and feature bloat to a minimum.

**Comment by TGTGamer** [comment]
@peter-evans the spec I'm working on is a specification for "allconfig.json" to reduce the amount of A. Configuration files in repositories, and B. runtime of actions. Through using JSON strings (which I'm considering converting into byte arrays to save space) this data can be propagated as needed by actions. 

As GitHub secrets can be a max size of 64 KB it makes sense to use this to our advantage. I'm in the process of writing an action which saves settings to either Organisations or Repository secrets and intends to develop a collection of actions and systems which use this secret. 

So the specification of the "allConfig" setup is something still in writing, to ensure I am 100% sure that it works as intended before I start integrating with other applications, but the general concept is: AllConfig.json (rename-able) is the single file which stores all your configuration data for workflows which require advanced setups.

The changes would be basically: 

https://github.com/peter-evans/slash-command-dispatch/blob/762c957c6dddb1f0178fc5565ed8ba6fb26e673d/src/command-helper.ts#L130-L136

Becomes

```ts
 export function getCommandsConfigFromJson(json: string): Command[] { 
   var jsonConfig = JSON.parse(json) 
   if (jsonConfig.slash-command-dispatch) jsonConfig = jsonConfig.slash-command-dispatch // could be whatever you choose
   core.debug(`JSON config: ${inspect(jsonConfig)}`) 

```

**Comment by peter-evans** [comment]
So I gather your action can extract JSON from a secret into to either environment variables or a file during the workflow. Interesting idea.

Rather than modify this action, can I suggest that a good feature of your action would be to allow users to extract sub-sections of the JSON to a file. This would allow a user to create a file containing just the JSON property `slash-command-dispatch`. This could be an optional input to your action, otherwise it would output the entire JSON to file.
